### ISSUE TITLE
IllegalAccessError on plugin load

### ISSUE THREAD

**Issue by EggAllocationService** [funkemunky/Atlas#25]
```
java.lang.IllegalAccessError: class cc.funkemunky.api.utils.ClassScanner (in unnamed module @0x1ec53ac8) cannot access class jdk.internal.org.objectweb.asm.ClassReader (in module java.base) because module java.base does not export jdk.internal.org.objectweb.asm to unnamed module @0x1ec53ac8
        at cc.funkemunky.api.utils.ClassScanner.findPlugin(ClassScanner.java:226) ~[?:?]
        at cc.funkemunky.api.utils.ClassScanner.scanZip(ClassScanner.java:188) ~[?:?]
        at cc.funkemunky.api.utils.ClassScanner.scanPath(ClassScanner.java:106) ~[?:?]
        at cc.funkemunky.api.utils.ClassScanner.scanFile(ClassScanner.java:94) ~[?:?]
        at cc.funkemunky.api.utils.ClassScanner.scanFile(ClassScanner.java:43) ~[?:?]
        at cc.funkemunky.api.Atlas.initializeScanner(Atlas.java:225) ~[?:?]
        at cc.funkemunky.api.Atlas.onEnable(Atlas.java:119) ~[?:?]
```
I am running Amazon Coretto JDK 16.0.1 on MacOS 11.4.

**Comment by funkemunky** [comment]
This is fixed

**Comment by Enabledus** [comment]
It's really not.
