### ISSUE TITLE
Atlas canceles all attempt to join server no matter the circumstances

### ISSUE THREAD

**Issue by Gyztor** [funkemunky/Atlas#46]
```
[02:39:30 WARN]: [cc.funkemunky.api.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.RuntimeException: The received encoded string buffer length is longer than maximum allowed (1233 > 1020)
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:369) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:55) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:169) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:99) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:89) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.<init>(WrapperHandshakingClientHandshake.java:39) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketReceive(InternalPacketListener.java:125) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:81) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:67) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:89) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:120) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:39:30 WARN]: [cc.funkemunky.api.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex: 74, writerIndex: 16 (expected: 0 <= readerIndex <= writerIndex <= capacity(256))
        at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at cc.funkemunky.api.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readerIndex(ByteBufOperatorModernImpl.java:44) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readerIndex(ByteBufHelper.java:39) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:374) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:55) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:169) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:99) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:89) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.<init>(WrapperHandshakingClientHandshake.java:39) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketReceive(InternalPacketListener.java:125) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:81) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:67) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at cc.funkemunky.api.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:89) ~[AtlasBukkit-1.12.1-test1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:39:30 INFO]: UUID of player GyztorMizirath is 951816b1-7d5e-484d-865f-495b25544d56
[02:39:30 INFO]: GyztorMizirath lost connection: Internal Exception: io.netty.handler.codec.EncoderException: cc.funkemunky.api.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 3 to a PacketType constant. Bound: CLIENT, Connection state: HANDSHAKING, Server version: 1.18.2
```
i think this `java.lang.RuntimeException: The received encoded string buffer length is longer than maximum allowed (1233 > 1020)` is due to an authenticater encryption to the backend servers to stop people from directly skipping the bungeecord (and the auth) to join backend servers. This error will kick the player with `ReadTimeoutException: null` too.

I was attempting to build the plugin to fully ensure issue https://github.com/funkemunky/Atlas/issues/44 was actually properly fixed and found this error that wouldnt let me join at all. I will try to find the commit on where this error appears too since someone else has been able to build the plugin and run it without any issues (by their claims in https://github.com/funkemunky/Atlas/issues/44 )

**Comment by Gyztor** [comment]
Bump

**Comment by Gyztor** [comment]
So i have found out this error occurs no matter what, even if i have my authentication/encryption to backend servers off plugin off
Edit: i can now also confirm that even when using the release latest it still has this error. It seems to be something new to the 1.12.x

**Comment by Gyztor** [comment]
as of commit b42f76df3104a1ad8560aeb444512d4bd155cc08 this seems to have been fixed i think. If anyone else wants to confirm if it works fine for them but for me so far it seems to be good.
