### ISSUE TITLE
error on server start

### ISSUE THREAD

**Issue by SladeGit** [funkemunky/Atlas#50]
[21:20:43 ERROR]: Error occurred while enabling Atlas v1.12.1.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at cc.funkemunky.api.utils.MiscUtils$1.<clinit>(MiscUtils.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:238) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-161]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-161]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: MinecraftVersion
        at cc.funkemunky.api.reflections.Reflections.getNMSClass(Reflections.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.tinyprotocol.api.ProtocolVersion.fetchGameVersion(ProtocolVersion.java:77) ~[Atlas.jar:?]
        at cc.funkemunky.api.tinyprotocol.api.ProtocolVersion.<clinit>(ProtocolVersion.java:61) ~[Atlas.jar:?]
        ... 16 more
[21:20:43 INFO]: [Atlas] Disabling Atlas v1.12.1.1
[21:20:43 ERROR]: Error occurred while disabling Atlas v1.12.1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class cc.funkemunky.api.utils.MiscUtils
        at cc.funkemunky.api.Atlas.alog(Atlas.java:495) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.alog(Atlas.java:488) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.onDisable(Atlas.java:174) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-161]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-161]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at cc.funkemunky.api.utils.MiscUtils$1.<clinit>(MiscUtils.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:238) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 9 more

**Comment by funkemunky** [comment]
What version of Minecraft did you have this issue on?

**Comment by SladeGit** [comment]
PaperSpigot latest
mc 1.19.2
latest plugin build

error on server start

**Comment by SladeGit** [comment]
Now on start


[19:16:45 ERROR]: Error occurred while enabling Atlas v1.12.1.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at cc.funkemunky.api.utils.MiscUtils$1.<clinit>(MiscUtils.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:238) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-173]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-173]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-173]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-173]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-173]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-173]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-173]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: MinecraftVersion
        at cc.funkemunky.api.reflections.Reflections.getNMSClass(Reflections.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.tinyprotocol.api.ProtocolVersion.fetchGameVersion(ProtocolVersion.java:77) ~[Atlas.jar:?]
        at cc.funkemunky.api.tinyprotocol.api.ProtocolVersion.<clinit>(ProtocolVersion.java:61) ~[Atlas.jar:?]
        ... 16 more

**Comment by tt-thoma** [comment]
Same Error
Pufferfish (paper fork)
mc 1.20.1
latest build

**Comment by tt-thoma** [comment]
Oh wow necroposting sorry
