### ISSUE TITLE
Error occurred while enabling Atlas v1.12.1.1 (Is it up to date?)

### ISSUE THREAD

**Issue by tt-thoma** [funkemunky/Atlas#57]
I really wanna use Kauri, but there is an issue with Atlas

> **Server**: Pufferfish 1.20.1 - Build 27 (979d3a2)
> **Plugins**: Atlas v1.12.1.1 Release (not bungee)
> **Tested on**: Windows 11 
> **Java version**:
> openjdk 17.0.8 2023-07-18 LTS
> OpenJDK Runtime Environment Zulu17.44+15-CA (build 17.0.8+7-LTS)
> OpenJDK 64-Bit Server VM Zulu17.44+15-CA (build 17.0.8+7-LTS, mixed mode, sharing)

**Trace log**:
```
[19:41:31 INFO]: [Atlas] Enabling Atlas v1.12.1.1
[19:41:31 INFO]: Loading class names...
[19:41:31 INFO]: Found file: file:/C:/Users/Administrateur/Downloads/Programs/Pufferfish/versions/1.20.1/pufferfish-1.20.1.jar
[19:41:31 ERROR]: Error occurred while enabling Atlas v1.12.1.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:97) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:238) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: Entity
        at cc.funkemunky.api.reflections.Reflections.getNMSClass(Reflections.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.reflections.impl.MinecraftReflection.<clinit>(MinecraftReflection.java:34) ~[Atlas.jar:?]
        ... 16 more
[19:41:31 INFO]: [Atlas] Disabling Atlas v1.12.1.1
[19:41:31 ERROR]: Error occurred (in the plugin loader) while disabling Atlas v1.12.1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class cc.funkemunky.api.utils.MiscUtils
        at cc.funkemunky.api.Atlas.alog(Atlas.java:495) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.alog(Atlas.java:488) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.onDisable(Atlas.java:174) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:97) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:238) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        ... 10 more
```

**Comment by tt-thoma** [comment]
Interesting... I got another error after I made an empty `config.yml` file in the Atlas directory (with the plugins)

```
[19:53:25 INFO]: [Atlas] Enabling Atlas v1.12.1.1
[19:53:25 ERROR]: Error occurred while enabling Atlas v1.12.1.1 (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
        at cc.funkemunky.api.utils.config.YamlConfiguration$1$1.<init>(YamlConfiguration.java:30) ~[Atlas.jar:?]
        at cc.funkemunky.api.utils.config.YamlConfiguration$1.initialValue(YamlConfiguration.java:29) ~[Atlas.jar:?]
        at cc.funkemunky.api.utils.config.YamlConfiguration$1.initialValue(YamlConfiguration.java:25) ~[Atlas.jar:?]
        at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
        at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
        at cc.funkemunky.api.utils.config.YamlConfiguration.load(YamlConfiguration.java:182) ~[Atlas.jar:?]
        at cc.funkemunky.api.utils.config.YamlConfiguration.load(YamlConfiguration.java:155) ~[Atlas.jar:?]
        at cc.funkemunky.api.utils.config.YamlConfiguration.load(YamlConfiguration.java:167) ~[Atlas.jar:?]
        at cc.funkemunky.api.utils.config.YamlConfiguration.load(YamlConfiguration.java:127) ~[Atlas.jar:?]
        at cc.funkemunky.api.utils.config.YamlConfiguration.load(YamlConfiguration.java:119) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:241) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:53:25 INFO]: [Atlas] Disabling Atlas v1.12.1.1
[19:53:26 INFO]: Loading class names...
[19:53:26 INFO]: Found file: file:/C:/Users/Administrateur/Downloads/Programs/Pufferfish/versions/1.20.1/pufferfish-1.20.1.jar
[19:53:26 ERROR]: Error occurred (in the plugin loader) while disabling Atlas v1.12.1.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:97) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.alog(Atlas.java:495) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.alog(Atlas.java:488) ~[Atlas.jar:?]
        at cc.funkemunky.api.Atlas.onDisable(Atlas.java:174) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: Entity
        at cc.funkemunky.api.reflections.Reflections.getNMSClass(Reflections.java:83) ~[Atlas.jar:?]
        at cc.funkemunky.api.reflections.impl.MinecraftReflection.<clinit>(MinecraftReflection.java:34) ~[Atlas.jar:?]
        ... 19 more
```

**Comment by tt-thoma** [comment]
Paper 1.21.1 - build 119
Fresh, first start

Duplicate of https://github.com/funkemunky/Kauri/issues/68#issuecomment-2395139266 , just for Atlas

**Plugins:**
- [GriefPrevention 16.18.4](https://dev.bukkit.org/projects/grief-prevention/files/5471866)
- [Atlas 1.12.1.1](https://github.com/funkemunky/Atlas/releases/tag/1.12.1.1)
- [Kauri API 2.19.2](https://github.com/funkemunky/Kauri/releases/tag/2.19.2)
- [Kauri Detections 2.19.2](https://github.com/funkemunky/Kauri/releases/tag/2.19.2)
- [Kauri Impl 2.19.2](https://github.com/funkemunky/Kauri/releases/tag/2.19.2)

**Error enabling Atlas**
```
[14:08:56 INFO]: [Atlas] Enabling Atlas v1.12.1.1
[14:08:56 ERROR]: Error occurred while enabling Atlas v1.12.1.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at Atlas.jar/cc.funkemunky.api.reflections.impl.MinecraftReflection.<clinit>(MinecraftReflection.java:34) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:97) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.loadConfig(Atlas.java:238) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at Atlas.jar/cc.funkemunky.api.reflections.Reflections.<clinit>(Reflections.java:44) ~[Atlas.jar:?]
        ... 17 more
[14:08:56 INFO]: [Atlas] Disabling Atlas v1.12.1.1
[14:08:56 ERROR]: Error occurred while disabling Atlas v1.12.1.1
java.lang.NoClassDefFoundError: Could not initialize class cc.funkemunky.api.utils.MiscUtils
        at Atlas.jar/cc.funkemunky.api.Atlas.alog(Atlas.java:495) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.alog(Atlas.java:488) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.onDisable(Atlas.java:174) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at Atlas.jar/cc.funkemunky.api.reflections.impl.MinecraftReflection.<clinit>(MinecraftReflection.java:34) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:97) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.loadConfig(Atlas.java:238) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        ... 10 more
```

Full logs: https://mclo.gs/sMhzyym

**Comment by Matt-MX** [comment]
I would not recommend using this since it's so outdated and clearly not maintained

**Comment by tt-thoma** [comment]
> I would not recommend using this since it's so outdated and clearly not maintained

The issue is the main plugin using Atlas (Kauri) IS updated, and I really wish this one could be too
